articles/urls.py
from django.urls import path
from articles import views

app_name = 'articles'
urlpatterns = [
    path('index/', views.index),
    path('dinner/<str:name>', views.dinner),
    path('review/', views.review, name = 'review'),
    path('create_review/', views.create_review, name = 'create_review')
]

django_tutorial/urls.py
from django.contrib import admin
from django.urls import path, include
from articles import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    #path('foods/', include('foods.urls'))

]
   

articles/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length = 10)
    content = models.TextField()
    create_at = models.DateTimeField(auto_now_add = True) # 생성시에 자동으로 추가가 되겠다 라는 뜻임

foods/models.py
from django.db import models

# Create your models here.

articles/views.py
import random
from django.shortcuts import render

# Create your views here. #제일많이 작업하는곳
def index(request):
    return render(request, 'index.html')

def dinner(request, name):
    menus = [{"name" : "족발", "price" : 30000},{"name" : "치킨", "price" : 18000},{"name" : "피자", "price" : 13000},{"name" : "초밥", "price" : 21000},]
    pick = random.choice(menus)
    context = {
        'pick' : pick,
        'name' : name,
        'menus': menus
    }
    return render(request, 'dinner.html', context)   

def review(request):
    return render(request, 'review.html')

def create_review(request):
    content = request.POST.get('content')
    print(request.POST)
    context = {
        'content' : content,
    }  
    return render(request, 'review_result.html', context)

foods/views.py
from django.shortcuts import render

# Create your views here.

articles/templates/base.html
<h1>헤더부분작성</h1>

{% block content %} {% endblock %}
<h1>풋터 부분 작성</h1>

articles/templates/dinner.html
{% extends 'base.html' %} {% block content %}
<h1>오늘 {{name}}님의 저녁은 {{pick.name}} 입니다</h1>
<h1>메뉴리스트</h1>
<ul>
    {% for menu in menus %}
    <li>{{ menu.name }} : {{ menu.price}}원 </li>
    {% endfor %}
</ul>


{% if pick.price > 20000 %}
<p>비싸다</p>
{% elif pick.price > 10000 %}
<p>적절하다</p>
{% else %}
<p>싸다</p>
{% endif %} {% endblock %} 

articles/templates/index.html
<h1>거북이왕이 되기위해!</h1>

articles/templates/review.html
<form action="{% url 'articles:create_review' %}"  method = "POST">
   {% csrf_token %}
   <label for="content">보낼 메세지</label>
   <input type = "text" id="content" name="content" />
   <input type="submit" />
</form>   

articles/templates/review_result.html
<h1>보내서 받은 내용은 {{content}} </h1>